USE [Cafe]
GO

/****** Object:  Table [dbo].[TaxExemptions]    Script Date: 2/18/2014 12:21:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TaxExemptions](
	[Name] [varchar](100) NOT NULL,
	[TaxExempt] [bit] NOT NULL,
 CONSTRAINT [PK_TaxExemptions] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

